### ISSUE TITLE
Product data listing_image url should be relative

### ISSUE THREAD

**Issue by sebszocinski** [sellfino/Statamify#11]
If you add products on staging or local url, it will save that domain in the field and then not work on production etc...

Example:
```
listing_image: '<div class="statamify-thumb" style="background-image: url(https://sitename.test/glide-cache/containers/main/./image.png/380a0aa077ec2fb7b2f06ee336e6388d.png)"></div>'
```

Should be:
```
listing_image: '<div class="statamify-thumb" style="background-image: url(/glide-cache/containers/main/./image.png/380a0aa077ec2fb7b2f06ee336e6388d.png)"></div>'
```

**Comment by sebszocinski** [comment]
Also, thumbnail images are now part of core in 2.9 so we should use them instead of this method - but you probably already know this and working on it already 🥇

**Comment by tavando** [comment]
listing_image was removed from latest version, so no problems should occure with this anymore (products have to be updated though)
