### ISSUE TITLE
Default shipping option

### ISSUE THREAD

**Issue by sebszocinski** [sellfino/Statamify#22]
Hi, the store I am currently working on only has one shipping option (flat rate, $10) and is Australia only, so we don't need to select a country, but it appears there is no way to set a default country?

**Comment by tavando** [comment]
That's frontend job. If you don't want user to be able to select the country, you could add hidden selectbox/input with name "country" and value "AU" in the checkout

**Comment by sebszocinski** [comment]
Hmm that didn't work for me because you need to set shipping method via Ajax call according to your code... I did it this way and it's working but surely there is a better way. 

```

// SET DEFAULT SHIPPING TO AU

$.ajax({
	method: 'post',
	url: locale_url + 'statamify/cart/set-shipping',
	data: {
		shipping_country: 'AU',
		_token: $('meta[name="_token"]').attr('content')
	},
	success: function(res) {
		console.log('set shipping to AU')
	},
	error: function(err) {
		console.log(err)
		error(err.responseJSON.message)
	}
})
```

**Comment by sebszocinski** [comment]
Hi @tavando, This is working now with method above however I ran into a strange issue.

If you are shopping logged out and then get to checkout it auto selects the correct shipping method available and you can checkout fine... however if you then try to login (redirect back to checkout) now there is no shipping method available unless you do another hard reload.... then the shipping method is available and selected again?

Any ideas why this is?

I have added this to my shipping form....
`input(type="hidden" name="shipping[country]" value="AU")`

If I console log `shipping` it says `false` after the login redirect, every other time it shows the shipping options.

**Comment by sebszocinski** [comment]
Nevermind, I had my default address country saved as `Australia` and not `AU`
