### ISSUE TITLE
Broken with 2.9.6

### ISSUE THREAD

**Issue by blamejen** [sellfino/Statamify#9]
- Products fieldtype is getting error: Fieldtype [title] does not exist
- Statamify settings Tabs are not working.
- Overall admin style is broken

**Comment by tavando** [comment]
As I stated on Slack - Statamify works only with 2.8.12. When I find time,
I will finish making the update for newer version of Statamic (there are
lot of changes in new version and Statamify is not small addon - lot of
work is ahead)

Best regards,
*Lucas Szarzynski*
Full-stack Developer

*Tavando • Developers for Agencies*
hello@tavando.com
www.tavando.com

2018-06-04 12:52 GMT+02:00 Jen Yang <notifications@github.com>:
